infiniband: Adding infiniband.py in pxe & ahc
This is required as detect.py uses it unless you have :
    ./detect.py
    Traceback (most recent call last):
        File "./detect.py", line 33, in <module>
            import infiniband as ib
            ImportError: No module named infiniband